services:
  frontend:
    build:
      context: ./frontend 
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend

  backend:
    build:
      context: ./backend   
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/backend  
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:


